FROM node:12.10.0-alpine as builder

WORKDIR /usr/src

ENV path /usr/src/node_modules/.bin:$PATH

COPY package.json .
COPY yarn.lock .
RUN yarn
RUN yarn global add react-scripts@2.1.8 --silent

ARG REACT_APP_USERS_SERVICE_URL
ENV REACT_APP_USERS_SERVICE_URL $REACT_APP_USERS_SERVICE_URL
ARG NODE_ENV
ENV NODE_ENV $NODE_ENV

COPY . .
RUN yarn build

FROM nginx:1.15.9-alpine

RUN rm -rf /etc/nginx/conf.d
COPY conf /etc/nginx

COPY --from=builder /usr/src/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]